# Run this Action on creating a new tag matching "<library>-<version>-<build>"
# e.g., foobar-1.2.3-1
name: Release
on:
  push:
    tags:
    - '*-*-*'

jobs:
  build:
    outputs:
      NAME: ${{ steps.vars.outputs.NAME }}
      VERSION: ${{ steps.vars.outputs.VERSION }}
      BUILD: ${{ steps.vars.outputs.BUILD }}
    strategy:
      matrix:
        host: ["arm-linux-androideabi", "aarch64-linux-android",
               "i686-linux-android", "x86_64-linux-android"]

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set Build Variables
      id: vars
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        TAG=$(basename $TAG_NAME)
        NAME_VERSION="${TAG%-*}"
        echo "NAME=${NAME_VERSION%-*}" | tee -a ${GITHUB_OUTPUT}
        echo "VERSION=${NAME_VERSION#*-}" | tee -a ${GITHUB_OUTPUT}
        echo "BUILD=${TAG#*-*-}" | tee -a ${GITHUB_OUTPUT}

    - name: Build
      run: |
        ./build.sh \
            ${{ steps.vars.outputs.NAME }} \
            ${{ steps.vars.outputs.VERSION }} \
            ${{ steps.vars.outputs.BUILD }} \
            ${{ matrix.host }}

    - uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ matrix.host }}
        path: ${{ steps.vars.outputs.NAME }}/build/${{ steps.vars.outputs.VERSION }}/${{ matrix.host }}/*.tar.gz
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4.1.7
      with:
        path: dist
        merge-multiple: true

    - uses: ncipollo/release-action@v1.13.0
      with:
        name: ${{ needs.build.outputs.NAME }} ${{ needs.build.outputs.VERSION }}-${{ needs.build.outputs.BUILD }}
        body: ${{ needs.build.outputs.NAME }} ${{ needs.build.outputs.VERSION }} (build ${{ needs.build.outputs.BUILD }})
        artifacts: "dist/*"
